In [137]:
#!pip install xgboost

In [138]:
from xgboost import XGBClassifier

In [3]:
# lightGBM /XGboost <- tree기반 알고리즘 둘이 가장 많이 쓰인다.

In [139]:
from sklearn import datasets

In [140]:
digits=datasets.load_digits()

In [141]:
from sklearn.model_selection import train_test_split

In [142]:
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.2)

In [143]:
from sklearn.ensemble import RandomForestClassifier

In [144]:
rfc=RandomForestClassifier()

In [145]:
xgb=XGBClassifier()

In [9]:
xgb.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', ...)

In [10]:
xgb.score(x_train,y_train)

1.0

In [11]:
xgb.score(x_test,y_test)

0.9611111111111111

In [14]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [15]:
rfc.score(x_train,y_train)

1.0

In [17]:
rfc.score(x_test,y_test)

0.9833333333333333

--------------

In [19]:
docs=["the cat in the hat",
      "the cow jumped over the moon",
      "the cat mooed and the cow meowed",
      "the cat said to the cow cow you are not a cat"]

In [21]:
docs[1][0]

't'

In [39]:
docs_list=[]
for i in docs:
    for j in i.split(' '):
        docs_list.append(j)
    
    

In [42]:
len(set(docs_list))

17

In [44]:
voca=set(' '.join(docs).split())

In [47]:
voca

{'a',
 'and',
 'are',
 'cat',
 'cow',
 'hat',
 'in',
 'jumped',
 'meowed',
 'mooed',
 'moon',
 'not',
 'over',
 'said',
 'the',
 'to',
 'you'}

In [48]:
common_words= set(['a','to','the','in','and','are'])

In [50]:
voca_m=voca-common_words

In [51]:
voca_m

{'cat',
 'cow',
 'hat',
 'jumped',
 'meowed',
 'mooed',
 'moon',
 'not',
 'over',
 'said',
 'you'}

In [64]:
'cat' in docs[0]

True

In [72]:
number=0
sentence_dict={}
docs_dict={}
for i in docs:
    docs_dict={}
    for j in voca_m:
        #print(j)
        if j in i:
            docs_dict[j]=True
        else:
            docs_dict[j]=False
    sentence_dict[number]=docs_dict
    number+=1
        
    

In [73]:
sentence_dict

{0: {'moon': False,
  'mooed': False,
  'meowed': False,
  'cow': False,
  'said': False,
  'not': False,
  'hat': True,
  'jumped': False,
  'you': False,
  'over': False,
  'cat': True},
 1: {'moon': True,
  'mooed': False,
  'meowed': False,
  'cow': True,
  'said': False,
  'not': False,
  'hat': False,
  'jumped': True,
  'you': False,
  'over': True,
  'cat': False},
 2: {'moon': False,
  'mooed': True,
  'meowed': True,
  'cow': True,
  'said': False,
  'not': False,
  'hat': False,
  'jumped': False,
  'you': False,
  'over': False,
  'cat': True},
 3: {'moon': False,
  'mooed': False,
  'meowed': False,
  'cow': True,
  'said': True,
  'not': True,
  'hat': False,
  'jumped': False,
  'you': True,
  'over': False,
  'cat': True}}

In [76]:
[i for i in docs]

['the cat in the hat',
 'the cow jumped over the moon',
 'the cat mooed and the cow meowed',
 'the cat said to the cow cow you are not a cat']

In [80]:
dict_list=[]
for i in docs:
    dic={}
    for m in voca_m:
        dic[m]=m in i
    dict_list.append(dic)

In [81]:
dict_list

[{'moon': False,
  'mooed': False,
  'meowed': False,
  'cow': False,
  'said': False,
  'not': False,
  'hat': True,
  'jumped': False,
  'you': False,
  'over': False,
  'cat': True},
 {'moon': True,
  'mooed': False,
  'meowed': False,
  'cow': True,
  'said': False,
  'not': False,
  'hat': False,
  'jumped': True,
  'you': False,
  'over': True,
  'cat': False},
 {'moon': False,
  'mooed': True,
  'meowed': True,
  'cow': True,
  'said': False,
  'not': False,
  'hat': False,
  'jumped': False,
  'you': False,
  'over': False,
  'cat': True},
 {'moon': False,
  'mooed': False,
  'meowed': False,
  'cow': True,
  'said': True,
  'not': True,
  'hat': False,
  'jumped': False,
  'you': True,
  'over': False,
  'cat': True}]

In [100]:
doc_contains=[ { v: (v in d) for v in voca_m} for d in docs]

In [101]:
doc_count_contains=[ { v: (d.count(v)) for v in voca_m} for d in docs]

In [102]:
doc_count_contains

[{'moon': 0,
  'mooed': 0,
  'meowed': 0,
  'cow': 0,
  'said': 0,
  'not': 0,
  'hat': 1,
  'jumped': 0,
  'you': 0,
  'over': 0,
  'cat': 1},
 {'moon': 1,
  'mooed': 0,
  'meowed': 0,
  'cow': 1,
  'said': 0,
  'not': 0,
  'hat': 0,
  'jumped': 1,
  'you': 0,
  'over': 1,
  'cat': 0},
 {'moon': 0,
  'mooed': 1,
  'meowed': 1,
  'cow': 1,
  'said': 0,
  'not': 0,
  'hat': 0,
  'jumped': 0,
  'you': 0,
  'over': 0,
  'cat': 1},
 {'moon': 0,
  'mooed': 0,
  'meowed': 0,
  'cow': 2,
  'said': 1,
  'not': 1,
  'hat': 0,
  'jumped': 0,
  'you': 1,
  'over': 0,
  'cat': 2}]

In [84]:
import pandas as pd

In [107]:
dcs=pd.DataFrame(doc_contains)
dcs

moon  mooed  meowed    cow   said    not    hat  jumped    you   over    cat
0  False  False   False  False  False  False   True   False  False  False   True
1   True  False   False   True  False  False  False    True  False   True  False
2  False   True    True   True  False  False  False   False  False  False   True
3  False  False   False   True   True   True  False   False   True  False   True

In [105]:
dcs =dcs.sort_index(axis=1)

In [103]:
# 개수 구하기

In [96]:
dict_count_list=[]
for i in docs:
    dic={}
    for m in voca_m:
        dic[m]=i.count(m)
    dict_count_list.append(dic)

In [97]:
dict_count_list

[{'moon': 0,
  'mooed': 0,
  'meowed': 0,
  'cow': 0,
  'said': 0,
  'not': 0,
  'hat': 1,
  'jumped': 0,
  'you': 0,
  'over': 0,
  'cat': 1},
 {'moon': 1,
  'mooed': 0,
  'meowed': 0,
  'cow': 1,
  'said': 0,
  'not': 0,
  'hat': 0,
  'jumped': 1,
  'you': 0,
  'over': 1,
  'cat': 0},
 {'moon': 0,
  'mooed': 1,
  'meowed': 1,
  'cow': 1,
  'said': 0,
  'not': 0,
  'hat': 0,
  'jumped': 0,
  'you': 0,
  'over': 0,
  'cat': 1},
 {'moon': 0,
  'mooed': 0,
  'meowed': 0,
  'cow': 2,
  'said': 1,
  'not': 1,
  'hat': 0,
  'jumped': 0,
  'you': 1,
  'over': 0,
  'cat': 2}]

In [122]:
wcs=pd.DataFrame(dict_count_list)

In [123]:
wcs

moon  mooed  meowed  cow  said  not  hat  jumped  you  over  cat
0     0      0       0    0     0    0    1       0    0     0    1
1     1      0       0    1     0    0    0       1    0     1    0
2     0      1       1    1     0    0    0       0    0     0    1
3     0      0       0    2     1    1    0       0    1     0    2

In [92]:
from sklearn.feature_extraction.text import CountVectorizer #개수 몇 개인지 세어주는 라이브러리 위에 것과 동일

In [89]:
sparse=CountVectorizer(stop_words='english').fit_transform(docs)

In [90]:
sparse.todense()

matrix([[1, 0, 1, 0, 0, 0, 0, 0],
        [0, 1, 0, 1, 0, 0, 1, 0],
        [1, 1, 0, 0, 1, 1, 0, 0],
        [2, 2, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [109]:
dcs.sum(axis=0)

moon      1
mooed     1
meowed    1
cow       3
said      1
not       1
hat       1
jumped    1
you       1
over      1
cat       3
dtype: int64

In [112]:
# 빈도 수

In [111]:
doc_freq=pd.DataFrame(dcs.sum(axis=0)).T
doc_freq

moon  mooed  meowed  cow  said  not  hat  jumped  you  over  cat
0     1      1       1    3     1    1    1       1    1     1    3

In [114]:
# TF/IDF(inver Document Frequency)
# DF(Document Frequency) -> 특정단어가 등장한 문서의 수 숫자가 클수록 많이 등장한다.

In [ ]:
#TF(Term Frequency) -> 특정 문서에서 특정 단어의 등장 횟수

In [115]:
import numpy as np

In [118]:
pd.options.display.float_format='{:.2f}'.format

In [119]:
idf= np.log(len(docs)/doc_freq)

In [121]:
idf# 숫자가 낮을수록 많이 등장했다

moon  mooed  meowed  cow  said  not  hat  jumped  you  over  cat
0  1.39   1.39    1.39 0.29  1.39 1.39 1.39    1.39 1.39  1.39 0.29

In [126]:
tf_idf=wcs*idf.iloc[0]
tf_idf

moon  mooed  meowed  cow  said  not  hat  jumped  you  over  cat
0  0.00   0.00    0.00 0.00  0.00 0.00 1.39    0.00 0.00  0.00 0.29
1  1.39   0.00    0.00 0.29  0.00 0.00 0.00    1.39 0.00  1.39 0.00
2  0.00   1.39    1.39 0.29  0.00 0.00 0.00    0.00 0.00  0.00 0.29
3  0.00   0.00    0.00 0.58  1.39 1.39 0.00    0.00 1.39  0.00 0.58

In [127]:
from sklearn.preprocessing import Normalizer

In [128]:
Normalizer(norm='l1').fit_transform(tf_idf)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.82814449, 0.        , 0.        , 0.        ,
        0.17185551],
       [0.31176747, 0.        , 0.        , 0.0646976 , 0.        ,
        0.        , 0.        , 0.31176747, 0.        , 0.31176747,
        0.        ],
       [0.        , 0.41407225, 0.41407225, 0.08592775, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.08592775],
       [0.        , 0.        , 0.        , 0.10836276, 0.26109149,
        0.26109149, 0.        , 0.        , 0.26109149, 0.        ,
        0.10836276]])

In [129]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [133]:
vectorizer=TfidfVectorizer(norm='l1', stop_words='english')

In [130]:
sparse=TfidfVectorizer(norm='l1', stop_words='english').fit_transform(docs)

In [134]:
spars=vectorizer.fit_transform(docs)

In [132]:
sparse.todense()

matrix([[0.38960636, 0.        , 0.61039364, 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.24193237, 0.        , 0.37903381, 0.        ,
         0.        , 0.37903381, 0.        ],
        [0.19480318, 0.19480318, 0.        , 0.        , 0.30519682,
         0.30519682, 0.        , 0.        ],
        [0.35927972, 0.35927972, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.28144056]])

In [147]:
vectorizer.get_feature_names_out()

array(['cat', 'cow', 'hat', 'jumped', 'meowed', 'mooed', 'moon', 'said'],
      dtype=object)

In [146]:
spars.

<4x8 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Row format>