In [1]:
import pandas as pd
import numpy as np
import pickle
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings(action='ignore')
#모델
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score
from sklearn.preprocessing import LabelBinarizer

In [3]:
#### 0이 정상 1이 도용

In [2]:
df=pd.read_csv('creditcard.csv')

In [3]:
df.shape

(284807, 31)

In [4]:
df2=df.drop_duplicates()

In [1]:
# 정상결제 = 1 비정상결제=0

In [5]:
normal=df[df['Class']==1]
abnormal=df[df['Class']==0]

In [6]:
normal.shape

(492, 31)

In [7]:
abnormal.shape

(284315, 31)

In [8]:
normal2=df2[df2['Class']==1]
abnormal2=df2[df2['Class']==0]

In [9]:
normal.value_counts()

Time      V1          V2         V3          V4        V5          V6         V7          V8          V9         V10         V11        V12         V13        V14         V15        V16         V17         V18        V19        V20        V21         V22        V23        V24        V25        V26        V27        V28        Amount  Class
68207.0   -13.192671  12.785971  -9.906650   3.320337  -4.801176    5.760059  -18.750889  -37.353443  -0.391540  -5.052502    4.406806  -4.610756   -1.909488  -9.072711   -0.226074  -6.211557   -6.248145   -3.149247   0.051576  -3.493050   27.202839  -8.887017   5.303607  -0.639435   0.263203  -0.108877   1.269566   0.939407  1.00    1        6
94362.0   -26.457745  16.497472  -30.177317  8.904157  -17.892600  -1.227904  -31.197329  -11.438920  -9.462573  -22.187089   4.419997  -10.592305  -0.703796  -3.926207   -2.400246  -6.809890   -12.462315  -5.501051  -0.567940   2.812241  -8.755698    3.460893   0.896538   0.254836  -0.738097  -0.966564  -7.26

In [10]:
abnormal_sample=abnormal.sample(16000)

In [11]:
abnormal_sample

Time         V1        V2        V3        V4        V5        V6  \
117012   74511.0  -0.626805 -0.424621  2.017261 -3.030913 -1.201899 -0.991728   
276413  167075.0  -1.501551  1.226098 -1.643652 -3.558932  2.396342  2.875349   
23469    32775.0   1.022064  0.255781  1.021991  2.302591 -0.107022  0.958796   
283243  171466.0  -0.870827  0.804701  0.762027 -1.407733  0.159492 -0.101762   
184454  126250.0   0.653171 -2.925406 -1.089544  1.002451 -1.423641  0.564224   
...          ...        ...       ...       ...       ...       ...       ...   
61709    49950.0 -10.512320  9.252013 -5.950209 -0.184883 -4.561450  4.866034   
97847    66407.0  -1.301159  1.320489 -0.795812 -0.631952  2.037779  3.335848   
199069  132795.0  -1.492044 -1.160730  1.003144 -3.025052  0.065202 -0.142661   
186379  127079.0  -0.339845  1.303742 -0.955143 -0.450029  1.103685 -1.004285   
103562   68712.0  -0.383092  0.815345  1.144359  0.308999  0.441693  0.211770   

               V7         V8        V9  ...        V21       V22       V23  \
117012  -0.385952  -0.024155 -1.790264  ...   0.019222  0.227595 -0.195267   
276413  -0.044177   1.731214 -0.202459  ...  -0.230806 -0.924169  0.041114   
23469   -0.503759   0.437414 -0.668072  ...   0.248132  0.709157 -0.010628   
283243   0.176794   0.469974  0.556880  ...   0.331096  0.932523 -0.113698   
184454  -0.088629  -0.022090 -0.565647  ...   0.351298 -0.025612 -0.377706   
...           ...        ...       ...  ...        ...       ...       ...   
61709  -15.048849 -24.959702 -2.941175  ... -13.963731  3.471115  2.877462   
97847   -0.531101   1.671543 -0.865023  ...  -0.067059 -0.672883  0.169498   
199069  -1.154332   0.702706 -2.383516  ...  -0.024618 -0.247369 -0.389121   
186379   1.183913  -0.476387  0.669801  ...   0.095148  0.832729 -0.319271   
103562   0.841285   0.130856 -0.855266  ...   0.187501  0.467171 -0.156596   

             V24       V25       V26       V27       V28  Amount  Class  
117012  0.327938  0.025929 -0.427383 -0.056240  0.112331   10.40      0  
276413  0.700159  0.041468  0.402146  0.103002  0.090680    4.00      0  
23469  -0.283881  0.244532  0.139228  0.038877  0.013191   10.65      0  
283243  0.500843 -0.247153 -0.518323 -0.054774  0.123933   12.99      0  
184454  0.691659 -0.476816 -0.687343 -0.054286  0.096218  717.30      0  
...          ...       ...       ...       ...       ...     ...    ...  
61709  -0.812035 -0.323797 -0.051265 -0.494935  0.274491    1.98      0  
97847   0.947036 -0.208675 -0.723566 -0.333200  0.002110    4.99      0  
199069  0.060257  0.660735 -0.156303 -0.084270 -0.173146    8.80      0  
186379 -0.795225 -0.159992 -0.125458  0.302696  0.125043   20.00      0  
103562 -0.304932  0.215209 -0.338000  0.035660  0.012831   53.00      0  

[16000 rows x 31 columns]

In [12]:
new_dataset=pd.concat([abnormal_sample,normal])

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [14]:
new_dataset['Class'].value_counts()

0    16000
1      492
Name: Class, dtype: int64

In [15]:
df[df.duplicated()]

Time        V1        V2        V3        V4        V5        V6  \
33          26.0 -0.529912  0.873892  1.347247  0.145457  0.414209  0.100223   
35          26.0 -0.535388  0.865268  1.351076  0.147575  0.433680  0.086983   
113         74.0  1.038370  0.127486  0.184456  1.109950  0.441699  0.945283   
114         74.0  1.038370  0.127486  0.184456  1.109950  0.441699  0.945283   
115         74.0  1.038370  0.127486  0.184456  1.109950  0.441699  0.945283   
...          ...       ...       ...       ...       ...       ...       ...   
282987  171288.0  1.912550 -0.455240 -1.750654  0.454324  2.089130  4.160019   
283483  171627.0 -1.464380  1.368119  0.815992 -0.601282 -0.689115 -0.487154   
283485  171627.0 -1.457978  1.378203  0.811515 -0.603760 -0.711883 -0.471672   
284191  172233.0 -2.667936  3.160505 -3.355984  1.007845 -0.377397 -0.109730   
284193  172233.0 -2.691642  3.123168 -3.339407  1.017018 -0.293095 -0.167054   

              V7        V8        V9  ...       V21       V22       V23  \
33      0.711206  0.176066 -0.286717  ...  0.046949  0.208105 -0.185548   
35      0.693039  0.179742 -0.285642  ...  0.049526  0.206537 -0.187108   
113    -0.036715  0.350995  0.118950  ...  0.102520  0.605089  0.023092   
114    -0.036715  0.350995  0.118950  ...  0.102520  0.605089  0.023092   
115    -0.036715  0.350995  0.118950  ...  0.102520  0.605089  0.023092   
...          ...       ...       ...  ...       ...       ...       ...   
282987 -0.881302  1.081750  1.022928  ... -0.524067 -1.337510  0.473943   
283483 -0.303778  0.884953  0.054065  ...  0.287217  0.947825 -0.218773   
283485 -0.282535  0.880654  0.052808  ...  0.284205  0.949659 -0.216949   
284191 -0.667233  2.309700 -1.639306  ...  0.391483  0.266536 -0.079853   
284193 -0.745886  2.325616 -1.634651  ...  0.402639  0.259746 -0.086606   

             V24       V25       V26       V27       V28  Amount  Class  
33      0.001031  0.098816 -0.552904 -0.073288  0.023307    6.14      0  
35      0.000753  0.098117 -0.553471 -0.078306  0.025427    1.77      0  
113    -0.626463  0.479120 -0.166937  0.081247  0.001192    1.18      0  
114    -0.626463  0.479120 -0.166937  0.081247  0.001192    1.18      0  
115    -0.626463  0.479120 -0.166937  0.081247  0.001192    1.18      0  
...          ...       ...       ...       ...       ...     ...    ...  
282987  0.616683 -0.283548 -1.084843  0.073133 -0.036020   11.99      0  
283483  0.082926  0.044127  0.639270  0.213565  0.119251    6.82      0  
283485  0.083250  0.044944  0.639933  0.219432  0.116772   11.93      0  
284191 -0.096395  0.086719 -0.451128 -1.183743 -0.222200   55.66      0  
284193 -0.097597  0.083693 -0.453584 -1.205466 -0.213020   36.74      0  

[1081 rows x 31 columns]

In [16]:
X=new_dataset.drop('Class',axis=1)
Y=new_dataset.Class

In [31]:
Y.unique()

array([0, 1], dtype=int64)

In [17]:
real_x=df.drop('Class',axis=1)
real_y=df.Class

In [18]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=42)

## DecisionTreeClassifier

In [327]:
model=DecisionTreeClassifier(max_depth=7,random_state=42,criterion='entropy')

In [328]:
model.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=7, random_state=42)

In [329]:
model.score(x_train,y_train)

0.9968922913666338

In [330]:
model.score(x_test,y_test)

0.9930281903607153

In [331]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [332]:
pred=model.predict(x_test)

In [333]:
f1_score(pred,y_test)

0.8743169398907105

In [334]:
f1_score(pred,y_test,pos_label=0)

0.996414653156664

In [337]:
f1_score(pred,y_test,pos_label=1)

0.8743169398907105

In [335]:
real_pred2=model.predict(new_x)

In [336]:
f1_score(real_pred2,new_y,average='macro')

0.826636311648679

In [78]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [274]:
confusion_matrix(pred,y_test,labels=[0,1])

ValueError: Found input variables with inconsistent numbers of samples: [50099, 250492]

In [278]:
print(classification_report(pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     50017
           1       0.77      0.91      0.83        82

    accuracy                           1.00     50099
   macro avg       0.88      0.96      0.92     50099
weighted avg       1.00      1.00      1.00     50099



In [154]:
f1_score(pred,y_test,pos_label=1)

0.8700564971751412

In [81]:
f1_score(pred,y_test, average='macro')

0.9426467738810307

In [114]:
real_pred=model.predict(x)

In [115]:
f1_score(y,real_pred, average='macro')

0.5251949708558196

In [82]:
model.feature_importances_

array([0.        , 0.00953341, 0.0020141 , 0.        , 0.04540857,
       0.01453668, 0.00494157, 0.00924983, 0.01437867, 0.00322256,
       0.0225961 , 0.        , 0.01539454, 0.01342734, 0.79893243,
       0.01174037, 0.00723173, 0.00438763, 0.        , 0.        ,
       0.        , 0.00259766, 0.00640878, 0.0039275 , 0.        ,
       0.        , 0.        , 0.        , 0.01007051, 0.        ])

In [83]:
model.feature_names_in_

array(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9',
       'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18',
       'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27',
       'V28', 'Amount'], dtype=object)

In [84]:
pd.DataFrame(list(zip(model.feature_importances_,model.feature_names_in_)),columns=['Features','importance']).sort_values('importance', ascending=True)

Features importance
29  0.000000     Amount
0   0.000000       Time
1   0.009533         V1
10  0.022596        V10
11  0.000000        V11
12  0.015395        V12
13  0.013427        V13
14  0.798932        V14
15  0.011740        V15
16  0.007232        V16
17  0.004388        V17
18  0.000000        V18
19  0.000000        V19
2   0.002014         V2
20  0.000000        V20
21  0.002598        V21
22  0.006409        V22
23  0.003927        V23
24  0.000000        V24
25  0.000000        V25
26  0.000000        V26
27  0.000000        V27
28  0.010071        V28
3   0.000000         V3
4   0.045409         V4
5   0.014537         V5
6   0.004942         V6
7   0.009250         V7
8   0.014379         V8
9   0.003223         V9

### def f1_score(): 함수구현하기 + 파라미터로 pos_label도 추가하기 + average='macro'구현하기

In [ ]:
def f1_score(a):
    

-------------------

In [33]:
import pandas as pd
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

In [20]:
treemodel=DecisionTreeClassifier()

In [21]:
treemodel.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [22]:
param_tree={'criterion':['gini','entropy'],'max_depth':range(1,11)}

In [35]:
ss=ShuffleSplit(test_size=0.25,n_splits=10)

In [41]:
grid_model=GridSearchCV(treemodel,return_train_score=True, param_grid=param_tree, cv=ss, verbose=1,scoring='f1_macro')

In [42]:
grid_model.fit(X,Y)

Fitting 10 folds for each of 20 candidates, totalling 200 fits


GridSearchCV(cv=ShuffleSplit(n_splits=10, random_state=None, test_size=0.25, train_size=None),
             estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(1, 11)},
             return_train_score=True, scoring='f1_macro', verbose=1)

In [43]:
grid_model.best_score_

0.950427919977286

In [44]:
grid_model.best_estimator_.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [45]:
cross_val_score(grid_model,X,Y,cv=3)

Fitting 10 folds for each of 20 candidates, totalling 200 fits
Fitting 10 folds for each of 20 candidates, totalling 200 fits
Fitting 10 folds for each of 20 candidates, totalling 200 fits


array([0.75934922, 0.9320757 , 0.91743249])

In [46]:
preferred_params=grid_model.best_estimator_.get_params()

In [47]:
final_tree=DecisionTreeClassifier(**preferred_params)

In [48]:
final_tree.fit(X,Y)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [49]:
final_tree.score(X,Y)

0.9950885277710405